#!/bin/sh

set -o errexit
# must comment out pipefail for debian-based images
# set -o pipefail
set -o nounset


# N.B. If only .env files supported variable expansion...
# export CELERY_BROKER_URL="${REDIS_URL}"

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
python3 << END
import sys

import psycopg

try:
    print("Going to use psycopg which is psycopg3 to connect to postgres")
    psycopg.connect(
        "${DATABASE_URL}"
    )
    print("psycopg successfully connected to postgres")
except psycopg.OperationalError as err:
    print("Op error: {0}".format(err))
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
